# Generated by Django 4.2.4 on 2023-08-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('birth_date', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('credit', models.FloatField(default=0)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('birth_date', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('credit', models.FloatField(default=0)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('period', models.DurationField()),
                ('fee', models.FloatField(default=3.0)),
                ('annual_interest', models.FloatField(blank=True)),
                ('loan_created', models.DateTimeField(auto_now_add=True)),
                ('loan_funded', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Completed', 'Completed'), ('Problem', 'Problem')], default='Pending', max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_interest', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('offer_created', models.DateTimeField(auto_now_add=True)),
                ('offer_concluded', models.DateTimeField(blank=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.investor')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.loan')),
            ],
        ),
    ]
