# Generated by Django 4.2.4 on 2023-08-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('period', models.DurationField()),
                ('fee', models.FloatField(default=3.0)),
                ('annual_interest', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_funded', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('Completed', 'Completed'), ('Problem', 'Problem')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('credit', models.FloatField(default=0)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.person')),
            ],
            bases=('database.person',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.person')),
            ],
            bases=('database.person',),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annual_interest', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_concluded', models.DateTimeField(null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.loan')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.investor')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower'),
        ),
        migrations.AddField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.investor'),
        ),
    ]
