# Generated by Django 4.2.4 on 2023-08-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_borrower_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='annual_interest',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.investor'),
        ),
    ]
