# Generated by Django 4.2.4 on 2023-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_loan_loan_funded_alter_offer_offer_concluded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='borrower_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='investor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
